spring:
  application:
    name: logging-context-sample
  reactor:
    context-propagation: auto
client:
  base-url: https://rickandmortyapi.com/api

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"