apiVersion: apps/v1
kind: Deployment
metadata:
  name: webflux-kotlin-log-context
  labels:
    app: webflux-kotlin-log-context
spec:
  selector:
    matchLabels:
      app: webflux-kotlin-log-context
  template:
    metadata:
      labels:
        app: webflux-kotlin-log-context
    spec:
      containers:
        - name: backend
          image: jeanfernandes1997/webflux-kotlin-log-context:0.0.5
          ports:
            - containerPort: 8080
              name: ws-port
          resources:
            requests:
              cpu: "400m"
              memory: 512Mi
            limits:
              cpu: "700m"
              memory: 700Mi
---
apiVersion: v1
kind: Service
metadata:
  name: webflux-kotlin-log-context
  labels:
    app: webflux-kotlin-log-context
spec:
  type: NodePort
  ports:
    - name: http-traffic
      port: 8080
      targetPort: ws-port
  selector:
    app: webflux-kotlin-log-context

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-app-service-monitor
spec:
  selector:
    matchLabels:
      app: webflux-kotlin-log-context
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webflux-kotlin-log-context
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webflux-kotlin-log-context
  minReplicas: 3
  maxReplicas: 10

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webflux-kotlin-log-context-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: webflux-kotlin-log-context.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webflux-kotlin-log-context
                port:
                  number: 8080