apiVersion: apps/v1
kind: Deployment
metadata:
  name: rick-and-morty-api
  labels:
    app: rick-and-morty-api
spec:
  selector:
    matchLabels:
      app: rick-and-morty-api
  template:
    metadata:
      labels:
        app: rick-and-morty-api
    spec:
      volumes:
        - name: wiremock-data-volume
          configMap:
            name: wiremock-data
      containers:
        - name: backend
          image: wiremock/wiremock:3.7.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "700m"
              memory: 700Mi
            limits:
              cpu: "1200m"
              memory: 1024Mi
          volumeMounts:
            - name: wiremock-data-volume
              mountPath: /home/wiremock/mappings

---
apiVersion: v1
kind: Service
metadata:
  name: rick-and-morty-api
  labels:
    app: rick-and-morty-api
spec:
  ports:
    - name: http-traffic
      port: 8080
      targetPort: 8080
  selector:
    app: rick-and-morty-api

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rick-and-morty-api
spec:
  selector:
    matchLabels:
      app: rick-and-morty-api
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rick-and-morty-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rick-and-morty-api
  minReplicas: 5
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource