apiVersion: apps/v1
kind: Deployment
metadata:
  name: rick-and-morty-api
  labels:
    app: rick-and-morty-api
spec:
  selector:
    matchLabels:
      app: rick-and-morty-api
  template:
    metadata:
      labels:
        app: rick-and-morty-api
    spec:
      volumes:
        - name: wiremock-data-volume
          configMap:
            name: wiremock-data
      containers:
        - name: backend
          image: wiremock/wiremock:3.7.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "600m"
              memory: 512Mi
            limits:
              cpu: "800m"
              memory: 1024Mi
          volumeMounts:
            - name: wiremock-data-volume
              mountPath: /home/wiremock/mappings

---
apiVersion: v1
kind: Service
metadata:
  name: rick-and-morty-api
  labels:
    app: rick-and-morty-api
spec:
  type: NodePort
  ports:
    - name: http-traffic
      port: 8080
      targetPort: 8080
  selector:
    app: rick-and-morty-api

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rick-and-morty-api
spec:
  selector:
    matchLabels:
      app: rick-and-morty-api
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rick-and-morty-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rick-and-morty-api
  minReplicas: 1
  maxReplicas: 10

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rick-and-morty-api-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: rick-and-morty-api.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rick-and-morty-api
                port:
                  number: 8080